# This is an additional service until https://github.com/rancher/k3d/pull/488 gets in
apiVersion: v1
kind: Service
metadata:
  name: {{ template "coredns.fullname" . }}-nodeport
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: {{ template "coredns.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ template "coredns.name" . }}
  ports:
    - protocol: {{ .Values.service.proto }}
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.targetPort }}
