linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gocritic
    - gocyclo
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - lll
run:
  deadline: 3m
linters-settings:
  lll:
    line-length: 150
