apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: coredns-crd
network: k3d-action-bridge-network
ports:
- port: 1053:30053/tcp
  nodeFilters:
  - loadbalancer
- port: 1053:53/udp
  nodeFilters:
  - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik,metrics-server,local-storage
        nodeFilters:
          - loadbalancer:*
