apiVersion: v1
name: coredns 
description: A Helm chart for the k8s_crd CoreDNS plugin
type: application
version: 1.0.0
appVersion: 0.1.0

dependencies:
  - name: coredns
    repository: https://coredns.github.io/helm
    version: 1.14.0
