apiVersion: v1
kind: Service
metadata:
  name: coredns-tcp
  namespace: coredns
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: coredns
  ports:
  - name: tcp-53
    port: 53
    protocol: TCP
    targetPort: 53
    nodePort: 30053
