name: Terratest

on:
  pull_request:

jobs:
  terratest:
    runs-on: ubuntu-latest
    env:
      TAG: "ci"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: build
        run: make build
      - name: build image
        run: make image
      - name: k3d
        uses: AbsaOSS/k3d-action@v1.2.0
        with:
          cluster-name: "coredns-crd"
          args: >-
            -p "1053:53/udp@loadbalancer"
            --k3s-server-arg "--no-deploy=traefik,metrics-server"
      - name: test
        run: |
          make terratest
