name: Terratest

on:
  pull_request:

jobs:
  terratest:
    runs-on: ubuntu-latest
    env:
      TAG: "ci"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: build
        run: make build
      - name: build image
        run: make image
      - name: k3d
        uses: AbsaOSS/k3d-action@v1.3.1
        with:
          cluster-name: "coredns-crd"
          args: >-
            --config=k3d-cluster.yaml
      - name: test
        run: |
          make terratest
