name: Terratest

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.drawio'
      - '.spelling'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.svg'
      - '**.drawio'
      - '.spelling'

jobs:
  skip-check:
    runs-on: ubuntu-latest
    name: Skip the job?
    outputs:
          should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v3.4.1
      with:
        skip_after_successful_duplicate: 'true'
        do_not_skip: '["workflow_dispatch", "schedule"]'

  terratest:
    runs-on: ubuntu-18.04
    env:
      TAG: "ci"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build
        run: make build
      - name: build image
        run: make image
      - name: k3d
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: "coredns-crd"
          args: >-
            --config=k3d-cluster.yaml
      - name: test
        run: |
          make terratest
